project:
  type: book
  output-dir: docs
  resources:
    - "files"
    - "images"

book:
  title: "Diagnostic Measurement: Theory, Methods, and Applications"
  subtitle: "Companion website"
  author:
    - "André A. Rupp"
    - "Jonathan Templin"
    - "Robert A. Henson"
  date: today
  repo-url: https://github.com/jonathantemplin/DCMbook
  repo-actions: [issue]
  page-navigation: true
  search: true
  chapters:
    - index.qmd
    - chapters/book-reviews.qmd
    - chapters/chapter-exercises.qmd
    - chapters/estimating-dcms-mplus.qmd
    - chapters/r-functions.qmd
    - chapters/sas-macro.qmd
    - chapters/errata.qmd

format:
  html:
    theme: cosmo
    toc: true
